- view-user/src/components/common/Header/Header.module.css
- view-user/src/components/common/Header/Header.tsx
- view-user/src/components/common/Modal/Modal.module.css
- view-user/src/components/common/Modal/Modal.tsx
- view-user/src/components/common/Modal/index.ts
- view-user/src/components/common/index.ts
- view-user/src/styles/Home.module.css
resolve#16
抽選された最新の番号を表示するモーダルを作成した。
（使われるボタンのデザインを何かに統一したい）
> [add] Create a modal to display results

- .gitignore
- cloudflare/prod/config.yml
- docker-compose.prod.yml
- view-user/src/components/common/BingoResult/BingoResult.module.css
- view-user/src/components/common/BingoResult/BingoResult.tsx
- view-user/src/components/common/BingoResult/index.ts
- view-user/src/components/common/Header/Header.module.css
- view-user/src/components/common/index.ts
- view-user/src/pages/index.tsx
- view-user/src/styles/Home.module.css
- view-user/src/styles/globals.css
resolve #27
- bingo.envを共有するのでレビューするときは教えてください
- `docker compose -f docker-compose.prod.yml up`を実行し、`https://bingo.nutfes.net`と`https://bingo-admin.nutfes.net`にアクセスできるか確認お願いします。
- 何かあれば、比嘉華、大浦さん、のせあたりにメンションしてください！！！
- 参考文献`https://blog.nutmeg.cloud/blog/post-20230320/`
いまは自分のローカルにデプロイしているだけでnutmegサーバorさくらVPSにはデプロイしていないので、コンテナ閉じるとアクセスできなくなります！！！
> [add] デプロイ設定の作成

- view-user/next.config.js
- view-user/package-lock.json
- view-user/package.json
- view-user/src/components/common/TestBingoList/TestBingoList.tsx
- view-user/src/utils/api_methods.ts
resolve #43 
- .envファイルにurlを書いたが，`process.env.WS_API_URL` で取得できなかった．
- apiのsubscriptionのreturnのところはchatGPTの返答をそのまま書いたら動いたのでよくわかっていない．
いい書き方があれば教えてください．
> issue43 WebSocket通信の実装

- docker-compose.yml
resolve #58
重複を削除しました。
- 私がマージするのでよし
> [mod] 重複していたenv_fileを削除

- Makefile
resolve #0
prod用のmakefile追加しました
> [mod] デプロイ用makeの作成

- view-admin/src/styles/Home.module.css
resolve #69 
管理者ページで背景が全体に広がらないことを修正。
> [fix] 背景が画面いっぱいに描画されるように修正

- docker-compose.prod.yml
resolve #76
prodの修正
ないかも
マージしてもいい？
> [mod] portの削除とenvファイルの指定

- view-admin/src/components/common/PrizeResult/PrizeResult.tsx
- view-admin/src/pages/index.tsx
- view-admin/src/pages/prizes/index.tsx
> [fix] コードの修正

- view-admin/src/components/common/JudgementModal/JudgementModal.module.css
resolve #102 
正誤判定モーダルのレスポンシブ対応を行いました。
> [add] 正誤判定モーダルのレスポンシブ対応

- view-admin/src/components/common/PrizeResult/PrizeResult.tsx
- view-user/src/components/common/PrizeResult/PrizeResult.tsx
resolve #113
loadingが画像の読み込み時にbooleanが切り替わるようになっていたので読み込みが終わったタイミングでfalseになるように修正しました。
- 画像を何回読み込んでもloadingがちゃんと消えるかどうか
> [mod] loadingがを画像が読み込み終わった後に非表示にするように修正

- view-admin/src/styles/Home.module.css
resolve #130 
管理者ページの背景の不具合を修正
> [fix] height→min-height

- view-admin/src/pages/index.tsx
resolve #124
Linkだと遷移しなかったので修正しました
- 景品追加ボタンをクリックしたちゃんと遷移するか
> [mod] ページ遷移をuseRouterに変更

- view-admin/src/components/common/PrizeResult/PrizeResult.tsx
- view-admin/src/pages/index.tsx
- view-admin/src/pages/prizes/index.tsx
- resolve #161 
景品表示ページにおいて、検索欄で景品名を絞り込めるようにする。
各景品にidを振り、Input欄への入力を元にfileterされる。
| 通常時 | 日本語検索 |
| ---- | ---- |
|![FireShot Capture 147 - Bingo Admin - localhost](https://github.com/NUTFes/nutfes-Bingo/assets/131145590/023f546d-9199-40e0-8c6f-6a344d33c734)|![FireShot Capture 148 - Bingo Admin - localhost](https://github.com/NUTFes/nutfes-Bingo/assets/131145590/2536be15-a4b7-450a-b035-2e1091736382)|
| 英語検索 | トグル切り替え |
| ---- | ---- |
| ![FireShot Capture 149 - Bingo Admin - localhost](https://github.com/NUTFes/nutfes-Bingo/assets/131145590/c659f262-a310-4400-8037-2a0365421dc5) |![FireShot Capture 151 - Bingo Admin - localhost](https://github.com/NUTFes/nutfes-Bingo/assets/131145590/ce21ca9d-940b-450f-8abe-15942d364504)|
> [add] 景品絞り込み機能

- view-admin/.eslintrc.json
- view-admin/.prettierrc.json
- view-admin/package-lock.json
- view-admin/package.json
- view-user/.eslintrc.json
- view-user/.prettierrc.json
- view-user/package-lock.json
- view-user/package.json
- resolve #165 
- user と adminにprettierを入れました．
prettier と eslint-config-prettier を npm install --save-devでインストールした．
> [feat] prettierの導入 + prettierに関わる部分のlintの設定

- view-admin/src/components/common/BingoResult/BingoResult.tsx
- view-admin/src/components/common/BingoResult/index.ts
- view-admin/src/components/common/Button/Button.tsx
- view-admin/src/components/common/Button/Button.types.ts
- view-admin/src/components/common/Button/index.tsx
- view-admin/src/components/common/Header/index.ts
- view-admin/src/components/common/JudgementModal/index.ts
- view-admin/src/components/common/PrizeResult/index.ts
- view-admin/src/components/common/index.ts
- view-admin/src/pages/_document.tsx
- view-admin/src/pages/api/auth/[...nextauth].ts
- view-admin/src/pages/api/hello.ts
- view-user/src/components/common/BingoIcon/index.ts
- view-user/src/components/common/BingoResult/BingoResult.tsx
- view-user/src/components/common/BingoResult/index.ts
- view-user/src/components/common/Button/Button.tsx
- view-user/src/components/common/Button/index.tsx
- view-user/src/components/common/Header/Header.tsx
- view-user/src/components/common/Header/index.ts
- view-user/src/components/common/Modal/Modal.tsx
- view-user/src/components/common/Modal/index.ts
- view-user/src/components/common/PrizeResult/PrizeResult.tsx
- view-user/src/components/common/PrizeResult/index.ts
- view-user/src/components/common/index.ts
- view-user/src/pages/_document.tsx
- view-user/src/pages/api/hello.ts
- view-user/src/pages/locales/en.ts
- view-user/src/pages/locales/ja.ts
> [fix] lintの修正

- view-user/src/components/common/PrizeResult/PrizeResult.module.css
- view-user/src/components/common/PrizeResult/PrizeResult.tsx
> [WIP] 景品表示ページのローディングアニメーションの表示条件を調整

- view-admin/src/pages/index.tsx
- resolve #193
admin画面の番号追加フォーム，削除フォームのバリデーションを1-99の範囲外の値の時に即時にバリデーションメッセージを表示するように変更した．
- view-admin/src/pages/index.tsxを変更
react-hook-formを使用した formDataCreateと，formDataDeleteに分割した．
modeをonChangeにして，値が変わった時に即時にバリデーションがかかるようにした．
> react-hook-formを番号追加/削除に分割，onChangeでバリデーションがかかるように変更

- view-admin/src/pages/index.tsx
- view-admin/src/styles/Home.module.css
resolve #184 
抽選番号として範囲外の数値が入力されたときに、送信ボタンをホバーしなくする。
Home.module.cssに以下を追加
.dummyButton{
border-radius: 0.5rem;
border: 2px solid #07033e;
background: #d9d9d9;
box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
color: #07033e;
font-weight: 700;
padding: 0.8rem 1rem;
}
index.tsxに以下を追加
{errors.submitNumber && (
<button type="submit" className={styles.dummyButton}>
送信
</button>
)}
1~99の数字を入力したとき
1~99以外の数字を入力したとき
- 抽選番号として1~99の数字を送信するときは送信ボタンがホバーする。
- 1~99以外の数字を入力すると送信ボタンはホバーしない。
-
一度送信ボタンを押さないと動かないです。
> [fix] ホバーしなくした！！

- view-admin/src/pages/index.tsx
- resolve #207 
developでerrors未定義のバグを修正
react-hook-formを2つに分割した時に定義した変数を使用した．
> erros未定義のバグを修正

- view-admin/src/pages/index.tsx
resolve #202 
react-hook-formで範囲外の数値が入力されたことを検知し、それに応じて送信ボタンのdisabledのtrue,falseを変化
react-hook-formのisValidで範囲外の数値かをブーリアン型で入手
ボタンにdisabledを追加し、isValidの値によって有効、無効を切り替える
> [fix]disabled属性の追加

- view-user/src/components/common/ReactionStampModal/ReactionStampModal.module.css
- view-user/src/components/common/ReactionStampModal/ReactionStampModal.tsx
- view-user/src/components/common/ReactionStampModal/index.ts
- view-user/src/components/common/index.ts
- view-user/src/pages/test/index.tsx
resolve #216 
リアクションスタンプの選択モーダルを作成
横幅375pxを基準に調整済み。propsでpositionを%で指定すると吹き出しの位置が変化します。
スタンプ押下後の処理は未定とのことで、その周辺は未実装です。
|![image](https://github.com/user-attachments/assets/2805018f-baa4-4733-a9e4-8a78123ae3ff)|![image](https://github.com/user-attachments/assets/07019b51-02f6-4cd8-9af1-98f4bb7460eb)|
|---|---|
> リアクションスタンプモーダルの作成

- view-user/src/components/common/NumberCardList/NumberCardList.module.css
- view-user/src/components/common/NumberCardList/NumberCardList.tsx
- view-user/src/components/common/NumberCardList/index.ts
- view-user/src/components/common/index.ts
- view-user/src/pages/test/index.tsx
resolve #223 
ナンバーカードをまとめるコンポーネントの作成
> name: NumberCardList
42ndみたいに3つずつ抽選番号を並べる
bingoNumberをmapで回してNumberCardSmallをpropsで渡せばいいと思う。
ただ設定で大きいカードを削除した場合もあるから先頭の数字を除いたものと除かないものをpropsで選べるといいかも
- firstNumberのbool値で先頭の数字を除くことができます。
|![image](https://github.com/user-attachments/assets/313d5b3a-f7a6-4f31-b1a0-9eb4d543dcf6)|![image](https://github.com/user-attachments/assets/cda30a3b-e3d8-4bd3-8b59-bceed0ca5449)|
|--|--|
> ナンバーカードをまとめるコンポーネントの作成

- view-admin/src/styles/Home.module.css
resolve #197 
範囲外の数値を入力すると送信ボタンが伸びてしまう現象を修正
.itemの中にalign-items: flex-start;を追加することで、子要素の伸縮をしないように設定した。
> [fix]送信ボタンの伸縮を無くす

- view-user/src/components/common/PrizeCard/PrizeCard.module.css
- view-user/src/components/common/PrizeCard/PrizeCard.tsx
- view-user/src/components/common/PrizeCardList/PrizeCardList.module.css
- view-user/src/components/common/PrizeCardList/PrizeCardList.tsx
- view-user/src/components/common/PrizeCardList/index.ts
- view-user/src/components/common/index.ts
- view-user/src/pages/test/index.tsx
resolve #233
景品をリスト表示させるコンポーネントを作成しました。
PrizeCardのflex colomnが正常に当たっていなかったため配置を調整しました。＆文字列の折り返しcssの追加
Listはgridを用いてtemplete-colomnsのrepertで3つずつ並べるようにしています。
> PrizeCardListコンポーネントの作成

- view-user/src/components/common/SettingsIcon/SettingsIcon.tsx
- view-user/src/components/common/SettingsIcon/index.ts
> settingsIconのsのつけ忘れを修正した

- view-user/package-lock.json
- view-user/package.json
- view-user/src/components/Layout/Layout.module.css
- view-user/src/components/Layout/Layout.tsx
- view-user/src/components/common/Header/Header.module.css
- view-user/src/components/common/Header/Header.tsx
- view-user/src/components/common/NavigationBar/NavigationBar.module.css
- view-user/src/pages/test/index.tsx
resolve #272
navbarは固定していたがヘッダーは固定されていなかったので修正した
navbarのようにfowardRefで高さを取得し、それをそのまま、main要素にpadding-topで当てている。
> headerを固定した

- view-user/src/components/Layout/Layout.module.css
- view-user/src/components/Layout/Layout.tsx
- view-user/src/components/common/IconFramework/IconFramework.tsx
- view-user/src/components/common/SettingsIcon/SettingsIcon.tsx
- view-user/src/components/common/ToggleButton/ToggleButton.tsx
- view-user/src/locales/en.ts
- view-user/src/locales/ja.ts
- view-user/src/pages/index.tsx
resolve #259 
- Settingsモーダルの作成
- ついでに一部を多言語化対応
- ToggleButtonコンポーネントの状態管理方法を修正
- IconFrameworkコンポーネントのinversion反映のための修正
- SettingsモーダルをModalコンポーネントを使用してLayout.tsxに追加
- Localeファイルを再作成し、ReachモーダルとSettingsモーダルのみ多言語化対応
|![image](https://github.com/user-attachments/assets/d77ec89a-abcf-4be5-a100-e23abefc2d49)|![image](https://github.com/user-attachments/assets/d0a26659-1cd4-4d75-b96f-7a184d193b6c)|
|--|--|
> Settingsモーダルの作成＆多言語化対応

- view-admin/src/components/common/JudgementModal/JudgementModal.module.css
- view-admin/src/components/common/JudgementModal/JudgementModal.tsx
resolve #205 
正誤判定モーダルを刷新しました。
- 43rdカラーに修正。
- 仮想テンキーの実装。
- インプット欄の直接選択機能を追加。
- 判定後の文字がインプット欄へ表示されるように。
実装時に抽選番号が取得して試せなかったので動作確認よろしくです。
> 正誤判定モーダルを刷新

- view-admin/src/components/common/BingoResult/BingoResult.module.css
- view-admin/src/components/common/Button/Button.module.css
- view-admin/src/components/common/Header/Header.module.css
- view-admin/src/components/common/JudgementModal/JudgementModal.module.css
- view-admin/src/components/common/PrizeResult/PrizeResult.module.css
- view-admin/src/pages/postPrizes/postPrizes.module.css
- view-admin/src/pages/prizes/prizes.module.css
- view-admin/src/styles/Home.module.css
resolve #265 
admin画面のデザイン変更
admin側の
・ホーム画面
・景品追加画面
・景品管理画面
・正誤判定画面
のデザインを変更した
ページごとにコミットを分けるつもりでしたが、分け方を間違えてしまいました。レビューしにくくなっていて申し訳ないです。
> admin画面のデザイン変更

- view-admin/package-lock.json
- view-admin/package.json
- view-user/package-lock.json
- view-user/package.json
- view-user/src/pages/screen/index.tsx
- resolve #298 
リアクションのアイコンを小さくした
アイコンサイズを従来の0.4倍の大きさにした。
当たり判定も小さくした
> リアクションのアイコンを小さくする

- view-admin/src/pages/index.tsx
- view-admin/src/styles/Home.module.css
- resolve #0
if sessionを復活させました。
バッググラウンドを変えました
> fix keycloakの復活

- view-user/src/components/common/ReactionStampModal/ReactionStampModal.module.css
- resolve #0
なし
いい感じのサイトからアニメーションを引っ張ってきました。
> スタンプにアニメーションを追加

- view-admin/next.config.js
- view-admin/src/components/common/PrizeResult/PrizeResult.module.css
- view-admin/src/components/common/PrizeResult/PrizeResult.tsx
- view-user/src/components/common/PrizeCard/PrizeCard.module.css
- view-user/src/components/common/PrizeCard/PrizeCard.tsx
- resolve #293 
- フォントカラーの変更
- オーバーレイ候補をいくつか作成
フォントカラーの修正
|![image](https://github.com/user-attachments/assets/618f0163-e120-439c-b41c-33fee8851817)|![image](https://github.com/user-attachments/assets/37c4ab03-a819-4506-9f8c-7098ad0a884d)|
|--|--|
> 景品のオーバーレイ修正＆フォントカラーの変更

- api/metadata/databases/databases.yaml
- api/metadata/databases/default/functions/functions.yaml
- api/metadata/databases/default/functions/public_decrement_latest_reach_log.yaml
- api/metadata/databases/default/functions/public_increment_latest_reach_log.yaml
- api/metadata/databases/default/tables/tables.yaml
- api/migrations/default/1720521696814_auto/up.sql
- view-admin/src/gql/reach_log.gql
- view-admin/src/pages/index.tsx
- view-admin/src/type/graphql.ts
- resolve #302
reachCountの増減を関数で行うようにしました。
hasura consoleで最新のデータを取得し増減を行う部分を関数化しました。
> reach増減APIの修正

- view-user/src/pages/screen/index.tsx
なし
- resolve #0
createdATのせいでスタンプがたくさん降下されてしまう問題があったため修正
> screenのcreatedAT取得を変更
